### ISSUE TITLE
kubeconfig -- server line should be customizable 

### ISSUE THREAD

**Issue by wibed** [tensor5/terraform-provider-talos#223]
the data statement for kubeconfig tries to open a conection to the server upon construction
the node should be on localhost as configured. 

```yaml
data "talos_cluster_kubeconfig" "this" {
  client_configuration = talos_machine_secrets.this.client_configuration
  node                 = "127.0.0.1"
}
```

yet....

```yaml
  apiVersion: v1
  kind: Config
  clusters:
  - name: cluster0
    cluster:
      server: https://10.0.48.20:6443
...
```

this causes me to reinit the terraform, excluding the kubeconfig because it tried to connect to 10.0.48.20:6443 which isnt on the network.
